# generated by datamodel-codegen:
#   filename:  camunda.json
#   timestamp: 2024-03-06T08:03:04+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CommonDataResponseVoid(BaseModel):
    code: Optional[str] = Field(None, description='响应码')
    data: Optional[Dict[str, Any]] = None
    msg: Optional[str] = Field(None, description='响应信息')


class StartProcessRequest(BaseModel):
    processDefKey: Optional[str] = Field(None, description='流程定义key')
    businessKey: Optional[str] = Field(None, description='流程业务主键taskId')
    tenantId: Optional[str] = Field(None, description='租户id')
    variables: Optional[Dict[str, Dict[str, Any]]] = Field(None, description='流程变量')


class ExecutionEntityDto(BaseModel):
    processDefinitionId: Optional[str] = None
    activityId: Optional[str] = None
    activityName: Optional[str] = None
    processInstanceId: Optional[str] = None
    parentId: Optional[str] = None
    superExecutionId: Optional[str] = None
    rootProcessInstanceId: Optional[str] = None
    superCaseExecutionId: Optional[str] = None


class VariableRequest(BaseModel):
    businessKey: Optional[str] = Field(None, description='流程业务主键')
    tenantId: Optional[str] = Field(None, description='租户id')
    processDefKey: Optional[str] = Field(None, description='模板定义id')
    variables: Optional[Dict[str, Dict[str, Any]]] = Field(None, description='流程变量')


class ActInfoRequest(BaseModel):
    businessKey: Optional[str] = Field(None, description='流程业务主键')
    tenantId: Optional[str] = Field(None, description='租户id')
    processDefKey: Optional[str] = Field(None, description='流程定义key')


class ActInfoResponse(BaseModel):
    actDefId: Optional[str] = Field(None, description='节点定义id')
    messageName: Optional[str] = Field(None, description='消息名')
    executionId: Optional[str] = Field(None, description='活动节点id')


class CommonDataResponseListActInfoResponse(BaseModel):
    code: Optional[str] = Field(None, description='响应码')
    data: Optional[List[ActInfoResponse]] = None
    msg: Optional[str] = Field(None, description='响应信息')


class CommonDataResponseActInfoResponse(BaseModel):
    code: Optional[str] = Field(None, description='响应码')
    data: Optional[ActInfoResponse] = None
    msg: Optional[str] = Field(None, description='响应信息')


class ReceivedTaskRequest(BaseModel):
    businessKey: Optional[str] = Field(None, description='流程业务主键')
    tenantId: Optional[str] = Field(None, description='租户id')
    processDefKey: Optional[str] = Field(None, description='模板定义id')
    messageName: Optional[str] = Field(None, description='消息名称')
    variables: Optional[Dict[str, Dict[str, Any]]] = Field(None, description='流程变量')


class ReceivedMessageEvent(BaseModel):
    businessKey: Optional[str] = Field(None, description='流程业务主键')
    tenantId: Optional[str] = Field(None, description='租户id')
    processDefKey: Optional[str] = Field(None, description='模板定义id')
    activityId: Optional[str] = Field(None, description='节点id')
    messageName: Optional[str] = None
    variables: Optional[Dict[str, Dict[str, Any]]] = Field(None, description='流程变量')


class ReceivedCommonRequest(BaseModel):
    businessKey: Optional[str] = Field(None, description='流程业务主键--orderGkey')
    tenantId: Optional[str] = Field(None, description='租户id')
    processDefKey: Optional[str] = Field(None, description='模板定义id')
    activityId: Optional[str] = Field(None, description='节点id')
    variables: Optional[Dict[str, Dict[str, Any]]] = Field(None, description='流程变量')


class CancelProcessRequest(BaseModel):
    businessKey: Optional[str] = Field(None, description='业务主键')
    tenantId: Optional[str] = Field(None, description='租户id')
    processDefKey: Optional[str] = Field(None, description='流程定义key值')
    cancelReason: Optional[str] = Field(None, description='取消原因')


class CommonDataResponseExecutionEntityDto(BaseModel):
    code: Optional[str] = Field(None, description='响应码')
    data: Optional[ExecutionEntityDto] = None
    msg: Optional[str] = Field(None, description='响应信息')
