# generated by datamodel-codegen:
#   filename:  integrator.json
#   timestamp: 2024-03-06T08:02:53+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
