# generated by datamodel-codegen:
#   filename:  pp.json
#   timestamp: 2024-03-26T08:58:59+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    pass
