# generated by datamodel-codegen:
#   filename:  pp.json
#   timestamp: 2024-03-18T08:32:09+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    pass
