# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protobuf/hello_world/hello_world.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2

HelloRequest = None

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*src/protobuf/hello_world/hello_world.proto\x12\nhelloworld\x1a\x19google/protobuf/any.proto\"t\n\nHelloReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x05 \x01(\r\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bHelloReply1\x12\x0f\n\x07message\x18\x01 \x01(\t2\x96\x02\n\tHelloWord\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x41\n\tSayHello1\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00(\x01\x12\x41\n\tSayHello2\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x30\x01\x12\x43\n\tSayHello3\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protobuf.hello_world.hello_world_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREPLY']._serialized_start=85
  _globals['_HELLOREPLY']._serialized_end=201
  _globals['_HELLOREQUEST']._serialized_start=203
  _globals['_HELLOREQUEST']._serialized_end=231
  _globals['_HELLOREPLY1']._serialized_start=233
  _globals['_HELLOREPLY1']._serialized_end=263
  _globals['_HELLOWORD']._serialized_start=266
  _globals['_HELLOWORD']._serialized_end=544
# @@protoc_insertion_point(module_scope)


